### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by cristianojs** [bendmorris/python-geocode#1]
Hi,

I am using Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32.

When I try to install geocode usinng pip or running setup.py the following erro occurs:

(venv) C:\learning-flask\venv>pip install geocode
Collecting geocode
  Using cached geocode-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ventiv\AppData\Local\Temp\pip-build-g72httt_\geocode\setup.py", line 2, in <module>
        from __init__ import __version__
      File "C:\Users\ventiv\AppData\Local\Temp\pip-build-g72httt_\geocode\__init__.py", line 3, in <module>
        from geocode import *
      File "C:\Users\ventiv\AppData\Local\Temp\pip-build-g72httt_\geocode\geocode.py", line 97
        print latlon(input)
                   ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ventiv\AppData\Local\Temp\pip-build-g72httt_\geocode\

Thanks.

**Comment by bendmorris** [comment]
Looks like you're using Python 3. This project is a few years old and only supports Python 2.

**Comment by cristianojs** [comment]
Yes,

 

I am using Python 3.5.2

 

Thank you for your replay.

 

Regards,

Cristiano José da Silva.

De: Ben Morris [mailto:notifications@github.com] 
Enviada em: quinta-feira, 25 de maio de 2017 15:40
Para: bendmorris/python-geocode <python-geocode@noreply.github.com>
Cc: Cristiano José da Silva <cristiano.js@gmail.com>; Author <author@noreply.github.com>
Assunto: Re: [bendmorris/python-geocode] Install Error (#1)

 

Looks like you're using Python 3. This project is a few years old and only supports Python 2.

**Comment by cristianojs** [comment]
Olá,

Eu acabei de assinar o abaixo-assinado "Queremos o fim das passagens de
primeira classe para os ministros do STF!" e queria saber se você pode
ajudar assinando também.

A nossa meta é conseguir 150.000 assinaturas e precisamos de mais apoio.
Você pode ler mais sobre este assunto e assinar o abaixo-assinado aqui:

http://chng.it/G6TW7hcyWk

Obrigado!
Cristiano José
